const TEAM_FLAGS: Record<string, string> = {
  algeria: "🇩🇿",
  argentina: "🇦🇷",
  australia: "🇦🇺",
  austria: "🇦🇹",
  belgium: "🇧🇪",
  "bosnia/herzeg.": "🇧🇦",
  "bosnia and herzegovina": "🇧🇦",
  brazil: "🇧🇷",
  canada: "🇨🇦",
  "cape verde": "🇨🇻",
  colombia: "🇨🇴",
  croatia: "🇭🇷",
  curaçao: "🇨🇼",
  curacao: "🇨🇼",
  "czech rep.": "🇨🇿",
  "czech republic": "🇨🇿",
  "dr congo": "🇨🇩",
  ecuador: "🇪🇨",
  egypt: "🇪🇬",
  england: "🏴",
  france: "🇫🇷",
  germany: "🇩🇪",
  ghana: "🇬🇭",
  haiti: "🇭🇹",
  "ir iran": "🇮🇷",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  "ivory coast": "🇨🇮",
  "côte d’ivoire": "🇨🇮",
  "cote d’ivoire": "🇨🇮",
  japan: "🇯🇵",
  jordan: "🇯🇴",
  mexico: "🇲🇽",
  morocco: "🇲🇦",
  netherlands: "🇳🇱",
  "new zealand": "🇳🇿",
  norway: "🇳🇴",
  panama: "🇵🇦",
  paraguay: "🇵🇾",
  portugal: "🇵🇹",
  qatar: "🇶🇦",
  "rep. of korea": "🇰🇷",
  "south korea": "🇰🇷",
  "saudi arabia": "🇸🇦",
  scotland: "🏴",
  senegal: "🇸🇳",
  "south africa": "🇿🇦",
  spain: "🇪🇸",
  sweden: "🇸🇪",
  switzerland: "🇨🇭",
  tunisia: "🇹🇳",
  turkey: "🇹🇷",
  usa: "🇺🇸",
  "united states": "🇺🇸",
  uruguay: "🇺🇾",
  uzbekistan: "🇺🇿",
};

export function teamFlag(team: string) {
  return TEAM_FLAGS[team.trim().toLowerCase()] || "🏆";
}

export function teamLabel(team: string) {
  return `${teamFlag(team)} ${team}`;
}
